#!/bin/bash

# These commands take this form
# ./ops [script] [option]

script=${1}
option=${2}

if [ -z $script ] ; then
  echo "please enter a command after ./ops"

elif [ $script == "setup" ] ; then
  rm -rf node_modules
  yarn install

elif [ $script == "start" ] ; then
  yarn start

elif [ $script == "dev" ] ; then
  yarn dev

elif [ $script == "export" ] ; then
  yarn build
  yarn export

elif [ $script == "test" ] ; then
  yarn test

elif [ $script == "build" ] ; then
  yarn build

elif [ $script == "ship" ] ; then
  yarn build
  yarn export
  git push origin master

fi



